Repository CA-G12/g-lancer, pull requests merged in 2022-10, with the labels that each got.

#3 file structure creating the server side relates #2
  package.json
  server/.eslintrc.json
  server/.gitignore
  server/__test__/index.ts
  server/app.ts
  server/controllers/index.ts
  server/db/index.ts
  server/helpers/index.ts
  server/index.ts
  server/interfaces/index.ts
  server/middlewares/index.ts
  server/models/index.ts
  server/package-lock.json
  server/package.json
  server/routes/index.ts
  server/tsconfig.json
  server/validation/index.ts
Labels: awaitting-review

#4 create file structure for client side relates #1
  client/.eslintrc.json
  client/.gitignore
  client/package-lock.json
  client/package.json
  client/public/favicon.ico
  client/public/index.html
  client/src/App.css
  client/src/App.tsx
  client/src/assets/logo.png
  client/src/components/index.tsx
  client/src/config.ts
  client/src/helpers/index.tsx
  client/src/index.tsx
  client/src/layouts/index.tsx
  client/src/pages/index.tsx
  client/tsconfig.json
Labels: chnages-requested

#13 7 database connection
  server/.env.example
  server/db/config/build.ts
  server/db/config/connection.ts
  server/db/config/init.sql
  server/package-lock.json
  server/package.json
Labels: awaitting-review

#15 feat: create the proposal model and its relation
  client/package-lock.json
  package-lock.json
  server/models/Proposal.ts
  server/models/index.ts
Labels: awaitting-review

#16 feat: create the user model relates #11
  server/models/index.ts
  server/models/user.ts
Labels: awaitting-review

#17 build: create freelancer module relates #8
  server/models/Freelancer.ts
Labels: awaitting-review

#23 build: create relations between models relates #20
  .vscode/settings.json
  client/package-lock.json
  server/models/Proposal.ts
  server/models/index.ts
  server/package-lock.json
Labels: approved

#26 fix: fix the init.sql file
  server/db/config/init.sql
Labels: approved

#30 db: add the fake data file and the categories json file relates #22
  client/categoris.json
  commitlint.config.js
  package.json
  server/db/config/build.ts
  server/db/config/connection.ts
  server/db/config/fakeData.ts
  server/models/Freelancer.ts
  server/models/Job.ts
  server/models/Proposal.ts
  server/models/User.ts
  server/package.json
Labels: awaitting-review

#33 refactor: devide pages into folders and create its css file relates #32
  client/src/pages/Client/index.tsx
  client/src/pages/Client/style.css
  client/src/pages/Freelancer/index.tsx
  client/src/pages/Freelancer/style.css
  client/src/pages/Job/index.tsx
  client/src/pages/Job/style.css
  client/src/pages/JobsSearch/index.tsx
  client/src/pages/JobsSearch/style.css
  client/src/pages/Landing/index.tsx
  client/src/pages/Landing/style.css
  client/src/pages/Login/index.tsx
  client/src/pages/Login/style.css
  client/src/pages/PageNotFound/index.tsx
  client/src/pages/PageNotFound/style.css
  client/src/pages/Signup/index.tsx
  client/src/pages/Signup/style.css
Labels: awaitting-review

#27 feat: create server with express
  server/app.ts
  server/index.ts
  server/package-lock.json
  server/package.json
  server/routes/index.ts
Labels: awaitting-review

#40 fix: edit the datatype in the price to integer
  server/db/config/fakeData.ts
  server/models/Job.ts
Labels: awaitting-review

#39 fix: edit file structure for server file relates #37
  server/package.json
  server/src/app.ts
  server/src/controllers/index.ts
  server/src/db/config/build.ts
  server/src/db/config/connection.ts
  server/src/db/config/fakeData.ts
  server/src/db/config/init.sql
  server/src/db/index.ts
  server/src/helpers/customError.ts
  server/src/helpers/index.ts
  server/src/index.ts
  server/src/interfaces/index.ts
  server/src/middlewares/error.ts
  server/src/middlewares/index.ts
  server/src/models/Freelancer.ts
  server/src/models/Job.ts
  server/src/models/Proposal.ts
  server/src/models/User.ts
  server/src/models/index.ts
  server/src/routes/index.ts
  server/src/validation/index.ts
Labels: done

#36 29 landing page
  client/categoris.json
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/assets/breadcrumb-bg.jpg
  client/src/assets/business.jpg
  client/src/assets/client.png
  client/src/assets/freelancer.jpg
  client/src/assets/graphic.jpg
  client/src/assets/hero.png
  client/src/assets/markiting.png
  client/src/assets/mobile-dev.webp
  client/src/assets/translation.webp
  client/src/assets/video-animation.jpg
  client/src/assets/voice.webp
  client/src/assets/web-dev.jpg
  client/src/categoris.js
  client/src/components/index.tsx
  client/src/components/landing/Category.tsx
  client/src/components/landing/Header.tsx
  client/src/components/landing/Hero.tsx
  client/src/components/landing/JoinClient.tsx
  client/src/components/landing/JoinFreelance.tsx
  client/src/components/landing/PopularCategories.tsx
  client/src/components/landing/index.tsx
  client/src/declration.d.ts
  client/src/pages/JobsSearch/index.tsx
  client/src/pages/Landing/index.tsx
  client/src/pages/Landing/style.css
  client/tsconfig.json
Labels: approved

#31 Create workflows
  .github/workflows/node.js.yml
  package.json
  server/__test__/index.ts
  server/__tests__/index.ts
  server/jest.config.js
  server/package-lock.json
  server/package.json
Labels: approved

#43 feat: create job card component relates #41
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/components/index.tsx
  client/src/components/jobCard/index.tsx
  client/src/components/jobCard/style.css
  client/src/pages/JobsSearch/index.tsx
Labels: awaitting-review

#47 feat: create the express wrpper function relates #64
  server/src/ExpressWrapper.ts
  server/src/interfaces/index.ts
  server/src/middlewares/error.ts
Labels: approved

#48 feat: create tab component relates #44
  client/src/components/index.tsx
  client/src/components/jobCard/index.tsx
  client/src/components/jobCard/style.css
  client/src/components/tab/index.tsx
  client/src/components/tab/style.css
  client/src/pages/JobsSearch/index.tsx
Labels: approved

#49 feat: add the filter for the job search page relates #45
  client/.eslintrc.js
  client/src/components/filter/index.tsx
  client/src/components/filter/style.css
  client/src/components/index.tsx
  client/src/pages/JobsSearch/index.tsx
Labels: awaitting-review

#55 feat: create the textEditor component and style it
  client/package-lock.json
  client/package.json
  client/src/components/TextEditor/index.tsx
  client/src/components/TextEditor/style.css
  client/src/components/index.tsx
Labels: approved

#58 54 get job api
  server/.env.example
  server/__tests__/jobs.ts
  server/src/ExpressWrapper.ts
  server/src/controllers/getJob.ts
  server/src/controllers/index.ts
  server/src/controllers/searchJobs.ts
  server/src/routes/jobs.ts
  server/src/validation/index.ts
Labels: awaitting-review

#59 feat: create the add proposal form and its validation
  client/package-lock.json
  client/package.json
  client/src/components/ProposalForm/index.tsx
  client/src/components/ProposalForm/style.css
  client/src/components/TextEditor/index.tsx
  client/src/components/TextEditor/style.css
  client/src/pages/Job/index.tsx
Labels: done

#60 feat: create component details and about jobs
  client/src/components/ProposalForm/style.css
  client/src/components/filter/style.css
  client/src/components/jobDetails/index.tsx
  client/src/components/jobDetails/style.css
  client/src/pages/Job/index.tsx
Labels: approved

#65 feat: create auth middlewares using passport relates #63
  .github/workflows/node.js.yml
  server/package-lock.json
  server/package.json
  server/src/middlewares/auth.ts
  server/src/middlewares/error.ts
  server/src/routes/index.ts
Labels: awaitting-review

#68 feat: create POST/proposal API and its tests #66
  .github/workflows/node.js.yml
  server/__tests__/index.test.ts
  server/__tests__/index.ts
  server/__tests__/jobs.ts
  server/__tests__/proposals.ts
  server/package.json
  server/src/ExpressWrapper.ts
  server/src/controllers/proposals.ts
  server/src/interfaces/index.ts
  server/src/middlewares/auth.ts
  server/src/routes/index.ts
  server/src/routes/proposals.ts
  server/src/validation/index.ts
  server/tsconfig.json
Labels: done

#70 feat: create the proposal job component and styling
  client/src/components/proposalJob/index.tsx
  client/src/components/proposalJob/style.css
  client/src/pages/Client/index.tsx
  server/src/db/config/fakeData.ts
Labels: awaitting-review

#71 51 react create the search page and include its components
  client/package-lock.json
  client/package.json
  client/src/App.css
  client/src/categoris.js
  client/src/components/filter/index.tsx
  client/src/components/filter/style.css
  client/src/components/jobCard/index.tsx
  client/src/components/tab/index.tsx
  client/src/components/tab/style.css
  client/src/helpers/fetchFunction.ts
  client/src/helpers/index.tsx
  client/src/pages/JobsSearch/index.tsx
  client/src/pages/JobsSearch/style.css
  server/src/controllers/searchJobs.ts
Labels: awaitting-review

#82 feat: create interface folder includes all interfaces&validation fold…
  client/src/components/ProposalForm/index.tsx
  client/src/components/TextEditor/index.tsx
  client/src/components/addJobForm/index.tsx
  client/src/components/filter/index.tsx
  client/src/components/jobCard/index.tsx
  client/src/components/jobDetails/index.tsx
  client/src/components/landing/Category.tsx
  client/src/components/proposalJob/index.tsx
  client/src/components/tab/index.tsx
  client/src/interfaces/index.ts
  client/src/pages/Client/index.tsx
  client/src/pages/Job/index.tsx
  client/src/pages/JobsSearch/index.tsx
  client/src/validation/index.ts
Labels: done

#84 81-create models interfaces
  server/package-lock.json
  server/package.json
  server/src/ExpressWrapper.ts
  server/src/controllers/getJob.ts
  server/src/controllers/proposals.ts
  server/src/controllers/searchJobs.ts
  server/src/db/config/fakeData.ts
  server/src/db/index.ts
  server/src/interfaces/index.ts
  server/src/middlewares/auth.ts
  server/src/models/Freelancer.ts
  server/src/models/Job.ts
  server/src/models/Proposal.ts
  server/src/models/User.ts
  server/src/validation/index.ts
Labels: approved

#86 76 back end delete job deleteapiv1jobid
  server/__tests__/index.test.ts
  server/__tests__/jobs.ts
  server/src/controllers/deleteJob.ts
  server/src/controllers/index.ts
  server/src/models/index.ts
  server/src/routes/jobs.ts
Labels: awaitting-review

#73 feat: post job request relates #72
  server/__tests__/jobs.ts
  server/src/controllers/deleteJob.ts
  server/src/controllers/getJob.ts
  server/src/controllers/index.ts
  server/src/controllers/jobs.ts
  server/src/controllers/searchJobs.ts
  server/src/routes/index.ts
  server/src/routes/jobs.ts
  server/src/validation/index.ts
Labels: done

#83 77 single job page
  client/src/App.css
  client/src/components/ProposalForm/index.tsx
  client/src/components/ProposalForm/style.css
  client/src/components/index.tsx
  client/src/components/jobCard/index.tsx
  client/src/components/jobDetails/index.tsx
  client/src/components/jobDetails/style.css
  client/src/interfaces/index.ts
  client/src/pages/Job/index.tsx
  client/src/pages/Job/style.css
Labels: awaitting-review

#89 85 middleware user data
  client/src/App.tsx
  server/src/middlewares/getUserData.ts
  server/src/routes/index.ts
Labels: awaitting-review

#95 feat: create get client info API relates #94
  server/__tests__/client.ts
  server/__tests__/index.test.ts
  server/src/controllers/client.ts
  server/src/db/config/fakeData.ts
  server/src/routes/client.ts
  server/src/routes/index.ts
Labels: done

#96 91 create user context
  client/src/App.tsx
  client/src/context/User.tsx
  client/src/context/index.jsx
  client/src/interfaces/index.ts
Labels: awaitting-review

#101 Login page
  client/src/assets/4957136 1.png
  client/src/pages/Login/index.tsx
  client/src/pages/Login/style.css
  client/src/validation/index.ts
Labels: awaitting-review

#98 feat: create GET/ freelancer API with its tests
  server/__tests__/freelancer.ts
  server/__tests__/index.test.ts
  server/__tests__/proposals.ts
  server/src/controllers/freelancer.ts
  server/src/controllers/index.ts
  server/src/interfaces/index.ts
  server/src/routes/freelancer.ts
  server/src/routes/index.ts
Labels: awaitting-review

#85 feat: receive proposals relates #78
  client/src/components/jobCard/index.tsx
  client/src/components/jobCard/style.css
  client/src/components/proposalJob/style.css
  client/src/interfaces/index.ts
  client/src/pages/Client/index.tsx
  client/src/pages/JobsSearch/index.tsx
Labels: changes-requested

#108 fix: edit the GET /Jobs controller
  client/src/components/jobCard/index.tsx
  client/src/interfaces/index.ts
  client/src/pages/Client/index.tsx
  client/src/pages/JobsSearch/index.tsx
  server/src/controllers/jobs.ts
Labels: awaitting-review

#104 103-Navbar component
  client/src/App.css
  client/src/App.tsx
  client/src/assets/logo2.png
  client/src/components/Navbar/index.tsx
  client/src/components/Navbar/style.css
  client/src/components/index.tsx
  client/src/context/index.jsx
  client/src/layouts/index.tsx
  client/src/pages/Landing/style.css
  client/src/pages/PageNotFound/index.tsx
  client/src/router.tsx
Labels: approved

#99 92 backend create the delete proposal for pending proposals
  server/__tests__/proposals.ts
  server/src/controllers/index.ts
  server/src/controllers/proposals.ts
  server/src/routes/proposals.ts
Labels: awaitting-review

#109 feat: create protected routes relates #100
  client/src/components/protectedRoute.tsx
  client/src/context/User.tsx
  client/src/router.tsx
Labels: awaitting-review

#115 feat: edit job card actions relates #105
  client/src/components/jobCard/index.tsx
  client/src/interfaces/index.ts
  client/src/pages/Client/index.tsx
  client/src/pages/Job/index.tsx
  client/src/pages/JobsSearch/index.tsx
  server/src/controllers/jobs.ts
Labels: awaitting-review

#113 feat: create PUT / freelancer Api and its validation
  server/__tests__/freelancer.ts
  server/src/controllers/freelancer.ts
  server/src/controllers/index.ts
  server/src/routes/freelancer.ts
  server/src/validation/index.ts
Labels: awaitting-review

#114 feat: create put api to edit proposal relates #111
  server/__tests__/proposals.ts
  server/src/controllers/index.ts
  server/src/controllers/proposals.ts
  server/src/routes/proposals.ts
  server/src/validation/index.ts
Labels: awaitting-review

#122 feat: create sign up form with stepper relates #117
  client/src/components/firstStepSignup/index.tsx
  client/src/components/firstStepSignup/style.css
  client/src/components/index.tsx
  client/src/components/signup/index.tsx
  client/src/components/signup/style.css
  client/src/interfaces/index.ts
  client/src/pages/Signup/index.tsx
  client/src/pages/Signup/style.css
  client/src/router.tsx
  client/src/validation/index.ts
Labels: awaitting-review

#121 feat: create POST/ login Api and its tests
  server/__tests__/auth.ts
  server/__tests__/index.test.ts
  server/package-lock.json
  server/package.json
  server/src/controllers/authentication.ts
  server/src/controllers/index.ts
  server/src/helpers/index.ts
  server/src/helpers/jwt.ts
  server/src/interfaces/index.ts
  server/src/routes/authentication.ts
  server/src/routes/index.ts
  server/src/validation/index.ts
Labels: awaitting-review

#123 feat: add the third step of sign up relates #118
  client/src/components/index.tsx
  client/src/components/signup/freelancerStep.tsx
  client/src/components/signup/index.tsx
  client/src/components/signup/style.css
  client/src/pages/Signup/index.tsx
  client/src/validation/index.ts
  server/src/controllers/jobs.ts
  server/src/models/Freelancer.ts
Labels: awaitting-review

#129 feat: freelancer sign up with test relates #127
  server/__tests__/auth.ts
  server/src/controllers/authentication.ts
  server/src/controllers/index.ts
  server/src/interfaces/index.ts
  server/src/routes/authentication.ts
  server/src/validation/index.ts
Labels: approved

#126 feat: create sign up api for user relates #125
  server/__tests__/auth.ts
  server/src/controllers/authentication.ts
  server/src/controllers/index.ts
  server/src/routes/authentication.ts
  server/src/validation/index.ts
Labels: awaitting-review

#133 132-fix freelancer token
  server/__tests__/freelancer.ts
  server/src/controllers/authentication.ts
  server/src/controllers/freelancer.ts
Labels: awaitting-review

#135 131 login page
  client/src/components/protectedRoute.tsx
  client/src/helpers/fetchFunction.ts
  client/src/helpers/index.tsx
  client/src/pages/JobsSearch/index.tsx
  client/src/pages/Login/index.tsx
  client/src/pages/Login/style.css
Labels: awaitting-review

#128 102 react create the client dashboard page and include its components
  client/src/components/addJobForm/index.tsx
  client/src/components/jobCard/index.tsx
  client/src/components/jobCard/style.css
  client/src/components/proposalJob/index.tsx
  client/src/interfaces/index.ts
  client/src/pages/Client/index.tsx
  client/src/pages/Client/style.css
Labels: awaitting-review

#142 feat: create not found component relates #141
  client/src/components/notFound/index.tsx
  client/src/components/notFound/style.css
  client/src/router.tsx
Labels: awaitting-review
